In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_excel(r"C:\Users\SALMAN PC\Downloads\online+retail\Online Retail.xlsx")

In [7]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [9]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     133626
Country             0
dtype: int64

In [6]:
df=df.dropna(subset=["Description"])

In [8]:
df.shape

(540455, 8)

In [10]:
basket=df.groupby(["InvoiceNo","Description"])["Quantity"].sum().unstack().fillna(0)

In [11]:
basket_encode=(basket>0).astype(int)
basket_bool=basket_encode.astype(bool)

In [12]:
from mlxtend.frequent_patterns import fpgrowth

In [31]:
frequent_itemsets=fpgrowth(basket_bool,min_support=0.03,use_colnames=True,max_len=3).sort_values(by=["support"])

In [32]:
from mlxtend.frequent_patterns import association_rules

rules = association_rules(
    frequent_itemsets,
    metric="confidence",
    min_threshold=0.5
)
rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']]
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({ROSES REGENCY TEACUP AND SAUCER }),frozenset({GREEN REGENCY TEACUP AND SAUCER}),0.043606,0.041520,0.031416,0.72045,17.351850,1.0,0.029606,3.428656,0.985336,0.584920,0.708341,0.73855
1,frozenset({GREEN REGENCY TEACUP AND SAUCER}),frozenset({ROSES REGENCY TEACUP AND SAUCER }),0.041520,0.043606,0.031416,0.75665,17.351850,1.0,0.029606,3.930120,0.983191,0.584920,0.745555,0.73855
2,frozenset({JUMBO BAG PINK POLKADOT}),frozenset({JUMBO BAG RED RETROSPOT}),0.049824,0.085576,0.033748,0.67734,7.915034,1.0,0.029484,2.834015,0.919470,0.331992,0.647144,0.53585

In [33]:
strong_rules = rules[rules['lift'] > 3]
strong_rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({ROSES REGENCY TEACUP AND SAUCER }),frozenset({GREEN REGENCY TEACUP AND SAUCER}),0.043606,0.041520,0.031416,0.72045,17.351850,1.0,0.029606,3.428656,0.985336,0.584920,0.708341,0.73855
1,frozenset({GREEN REGENCY TEACUP AND SAUCER}),frozenset({ROSES REGENCY TEACUP AND SAUCER }),0.041520,0.043606,0.031416,0.75665,17.351850,1.0,0.029606,3.930120,0.983191,0.584920,0.745555,0.73855
2,frozenset({JUMBO BAG PINK POLKADOT}),frozenset({JUMBO BAG RED RETROSPOT}),0.049824,0.085576,0.033748,0.67734,7.915034,1.0,0.029484,2.834015,0.919470,0.331992,0.647144,0.53585